{"name": "test_after", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestSearchXiaoMI' object has no attribute 'driver'", "trace": "self = <xiaomi_search_test.TestSearchXiaoMI object at 0x000002B4D5101D00>\n\n    def test_after(self):\n>       self.driver.quit()\nE       AttributeError: 'TestSearchXiaoMI' object has no attribute 'driver'\n\nxiaomi_search_test.py:31: AttributeError"}, "start": 1652930464560, "stop": 1652930464560, "uuid": "7d7aaa32-c4fd-495d-89a6-bc16e31eade7", "historyId": "f05341098672f448c3cceb01783922a1", "testCaseId": "5aa91493ff6541e6f5831205014ad52c", "fullName": "xiaomi_search_test.TestSearchXiaoMI#test_after", "labels": [{"name": "suite", "value": "xiaomi_search_test"}, {"name": "subSuite", "value": "TestSearchXiaoMI"}, {"name": "host", "value": "MFG-LANG1-MIRACL"}, {"name": "thread", "value": "67088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "xiaomi_search_test"}]}