{"name": "test_after", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestSearchXiaoMI' object has no attribute 'driver'", "trace": "self = <xiaomi_search_test.TestSearchXiaoMI object at 0x000002656261BD30>\n\n    def test_after(self):\n>       name_prompt = Alert(self.driver)\nE       AttributeError: 'TestSearchXiaoMI' object has no attribute 'driver'\n\nxiaomi_search_test.py:32: AttributeError"}, "start": 1653270955647, "stop": 1653270955647, "uuid": "48b518aa-0d52-450d-8043-29f326ef5123", "historyId": "f05341098672f448c3cceb01783922a1", "testCaseId": "5aa91493ff6541e6f5831205014ad52c", "fullName": "xiaomi_search_test.TestSearchXiaoMI#test_after", "labels": [{"name": "suite", "value": "xiaomi_search_test"}, {"name": "subSuite", "value": "TestSearchXiaoMI"}, {"name": "host", "value": "MFG-LANG1-MIRACL"}, {"name": "thread", "value": "10480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "xiaomi_search_test"}]}